services:
  jenkins-docker:
    image: docker:dind
    privillaged: true
    networks:
      - jenkins
    environment:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenins_home
